add more helpers to submodule
vimc/metrics-utils pull request #1
Opened 2018-10-09 09:17 UTC by littledice

2018-10-09 09:25 UTC, richfitz requested changes

2018-10-09 09:25 UTC, richfitz commented on metrics.py
> +        return None
What is your thinking behind returning `None` on falsy input? (here and below)

I'm also wondering - if we just store in the json: `time_secs` (via `datetime.datetime.utcnow().timestamp()`) as well as a (somewat) human readable one (`datetime.datetime.utcnow().isoformat()`) then we can both have something we can look at without going mad and avoid having to parse/manipulate times at all because we can just subtract the seconds

2018-10-09 09:25 UTC, richfitz commented on metrics.py
> +        now = datetime.now(timezone.utc)
I think we should use `.utcnow` and use UTC everywhere

2018-10-09 09:26 UTC, richfitz commented on metrics.py
> +        now = datetime.now(timezone.utc)
ah, though I see your code achieves exactly that sorry

2018-10-09 09:32 UTC, littledice commented on metrics.py
> +        return None
When there's no last available backup in barman some timestamps come through as `None`, so this just passes them through these methods unchanged. 

Agree storing seconds in the json makes things easy to deal with!

2018-10-11 08:41 UTC, richfitz approved these changes

2018-10-11 08:41 UTC, merged